// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskCRUD;

namespace TaskCRUD.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20220216121958_AddingData")]
    partial class AddingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TaskCRUD.Model.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = false,
                            Description = "description 1",
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            Description = "description 2",
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = 3,
                            Completed = false,
                            Description = "description 3",
                            Title = "Task 3"
                        },
                        new
                        {
                            Id = 4,
                            Completed = false,
                            Description = "description 4",
                            Title = "Task 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
